### ISSUE TITLE
 ReferenceError: Property 'ReadableStream' doesn't exist

### ISSUE THREAD

**Issue by sleep9** [ipfs/helia-verified-fetch#7]
Hello, just testing this with React-native and getting the following promise rejection...
**ReferenceError: Property 'ReadableStream' doesn't exist**
Reproducible by the following code
```const response = await verifiedFetch(`ipfs://bafybeihkoviema7g3gxyt6la7vd5ho32ictqbilu3wnlo3rs7ewhnp7lly`)```

**Comment by SgtPooki** [comment]
@sleep9 hey! If react native doesn't provide a polyfill for native web APIs, you will likely need to add a polyfill using your bundler. 

it looks like https://www.npmjs.com/package/react-native-polyfill-globals mentions some existing issues for this:

> [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) is not supported and, by extension, [Response.body](https://developer.mozilla.org/en-US/docs/Web/API/Body/body) is not implemented. Related discussions:
> * https://github.com/facebook/react-native/issues/27741
> * https://github.com/facebook/react-native/issues/12912
> * https://github.com/github/fetch/issues/198
> * https://github.com/github/fetch/issues/746

https://www.npmjs.com/package/web-streams-polyfill seems like a popular solution that may help out as well. Though I do not have deep experience with either.

Do you have an example repo we can use to reproduce this? Making sure we have basic instructions for getting react-native apps working would be great.

**Comment by sleep9** [comment]
My project is a git clone of the following repository, updated to hermes and moved to typescript...
https://github.com/ipfs-shipyard/js-libp2p-react-native

**Comment by SgtPooki** [comment]
it looks like you found the required module in https://github.com/ipfs/helia/issues/435, are you unblocked here?
